import { findingKeyForThreat, type ReportDelta } from "./baseline.js";
import { formatDeepDiveForDisplay } from "./deepDiveDisplay.js";
import { STRIDE_REFERENCE } from "./referenceStride.js";
import { resolveArchitectureRows, resolveThreatActorRows } from "./reportContext.js";
import {
  parseSecuritySignalsFromModel,
  sortSignalsBySeverity,
  signalsMatchingThreat,
} from "./signalGrounding.js";
import type { ThreatOutput } from "./schemas.js";

export type ThreatReportMeta = {
  title: string;
  projectRoot: string;
};

export type { ReportDelta } from "./baseline.js";

export type ThreatReportOptions = {
  /** Per-threat Markdown from a second LLM pass (deep-dive). */
  deepDiveById?: Record<string, string>;
  /** Include static STRIDE → CWE / OWASP appendix (default true). */
  includeReferenceAppendix?: boolean;
  /** Compared to `.threatlensai/baseline.json` from the previous run (NEW / UNCHANGED / resolved list). */
  delta?: ReportDelta;
};

const STRIDE_ORDER = ["S", "T", "R", "I", "D", "E"] as const;

function countByStride(threats: ThreatOutput["threats"]): Record<string, number> {
  const m: Record<string, number> = { S: 0, T: 0, R: 0, I: 0, D: 0, E: 0 };
  for (const t of threats) {
    m[t.stride] = (m[t.stride] ?? 0) + 1;
  }
  return m;
}

function countBySeverity(threats: ThreatOutput["threats"]): Record<string, number> {
  const m: Record<string, number> = {};
  for (const t of threats) {
    m[t.severity] = (m[t.severity] ?? 0) + 1;
  }
  return m;
}

export function buildThreatAssessmentMarkdown(
  systemModel: Record<string, unknown>,
  threats: ThreatOutput,
  meta: ThreatReportMeta,
  opts?: ThreatReportOptions,
): string {
  const deepDiveById = opts?.deepDiveById ?? {};
  const includeRef = opts?.includeReferenceAppendix !== false;
  const lines: string[] = [];
  lines.push(`# ${meta.title}`);
  lines.push("");
  lines.push(
    "This document was generated by **ThreatLensAI** for engineering and security review. Validate findings against the live architecture before relying on them for compliance sign-off.",
  );
  lines.push("");
  lines.push(`| Field | Value |`);
  lines.push(`| --- | --- |`);
  lines.push(`| **Generated (UTC)** | ${new Date().toISOString()} |`);
  lines.push(`| **Repository root** | \`${meta.projectRoot}\` |`);
  const ver = systemModel.version;
  lines.push(`| **System model version** | ${typeof ver === "number" ? String(ver) : "—"} |`);
  const fc = systemModel.file_count;
  lines.push(`| **Files indexed** | ${typeof fc === "number" ? fc : "—"} |`);
  const trunc = systemModel.truncated;
  lines.push(`| **Index truncated** | ${trunc === true ? "yes (tune .threatlensai.json)" : "no"} |`);
  lines.push("");

  const langs = systemModel.languages;
  const hasLangs =
    langs && typeof langs === "object" && langs !== null && !Array.isArray(langs);
  const gs = systemModel.go_summary as Record<string, unknown> | undefined;
  const hasGo = Boolean(gs && typeof gs === "object");
  const mermaidPreview =
    typeof systemModel.mermaid_flow === "string" ? systemModel.mermaid_flow.trim() : "";
  const hasMermaid = Boolean(mermaidPreview);
  const hasAnalystNotes = Boolean(threats.notes?.trim());
  const sigsForToc = sortSignalsBySeverity(parseSecuritySignalsFromModel(systemModel));
  const hasStaticSignals = sigsForToc.length > 0;
  const delta = opts?.delta;
  const showDeltaSection = delta != null;

  lines.push("## Table of contents");
  lines.push("");
  lines.push("- [Executive summary](#executive-summary)");
  if (showDeltaSection) {
    lines.push("- [Delta vs last run](#delta-vs-last-run)");
  }
  if (hasStaticSignals) {
    lines.push("- [Static security signals (code scan)](#static-security-signals-code-scan)");
  }
  lines.push("- [Data flows and trust boundaries](#data-flows-and-trust-boundaries)");
  lines.push("- [Threat sources](#threat-sources)");
  if (hasLangs) {
    lines.push("- [Language inventory](#language-inventory)");
  }
  if (hasGo) {
    lines.push("- [Go / HTTP summary](#go--http-summary-best-effort)");
  }
  if (hasMermaid) {
    lines.push("- [Architecture / trust flow](#architecture--trust-flow-mermaid)");
  }
  if (hasAnalystNotes) {
    lines.push("- [Analyst notes](#analyst-notes)");
  }
  lines.push("- [STRIDE threat register](#stride-threat-register)");
  lines.push("- [Detailed findings](#detailed-findings)");
  if (includeRef) {
    lines.push("- [STRIDE reference (CWE / OWASP pointers)](#stride-reference-cwe--owasp-pointers)");
  }
  lines.push("- [Disclaimer](#disclaimer)");
  lines.push("");

  const strideCounts = countByStride(threats.threats);
  const sevCounts = countBySeverity(threats.threats);
  lines.push("## Executive summary");
  lines.push("");
  lines.push(
    `This assessment lists **${threats.threats.length}** modeled threats. STRIDE and severity distributions summarize where review effort may cluster; they are **heuristic** and depend on how completely the repository was indexed.`,
  );
  lines.push("");
  if (delta) {
    if (!delta.hadBaseline) {
      lines.push(
        "*No prior baseline* (`.threatlensai/baseline.json` missing). All current findings are labeled **[NEW]**; the next run will compare against this snapshot.",
      );
      lines.push("");
    } else {
      const nNew = Object.values(delta.statusByKey).filter((s) => s === "NEW").length;
      const nUnchanged = Object.values(delta.statusByKey).filter((s) => s === "UNCHANGED").length;
      const nResolved = delta.resolved.length;
      const prev = delta.previousUpdatedAt
        ? ` (previous snapshot: **${delta.previousUpdatedAt}**)`
        : "";
      lines.push(
        `**Delta vs last run**${prev}: **${nNew}** new, **${nUnchanged}** unchanged, **${nResolved}** resolved.`,
      );
      lines.push("");
    }
  }
  lines.push("| STRIDE | Count |");
  lines.push("| --- | ---: |");
  for (const k of STRIDE_ORDER) {
    lines.push(`| ${k} (${strideLabel(k)}) | ${strideCounts[k] ?? 0} |`);
  }
  lines.push("");
  lines.push("| Severity | Count |");
  lines.push("| --- | ---: |");
  for (const k of ["CRITICAL", "HIGH", "MEDIUM", "LOW"] as const) {
    if (sevCounts[k] !== undefined) {
      lines.push(`| ${k} | ${sevCounts[k]} |`);
    }
  }
  lines.push("");

  if (delta != null) {
    lines.push("## Delta vs last run");
    lines.push("");
    if (!delta.hadBaseline) {
      lines.push(
        "Baseline **`.threatlensai/baseline.json`** was not present before this run. After a successful report, the next run will label findings **[NEW]**, **[UNCHANGED]**, or list **[RESOLVED]** items that disappeared from the register.",
      );
      lines.push("");
    } else if (delta.resolved.length > 0) {
      lines.push(
        "Findings below were present in the previous baseline but are **absent** from the current model output (remediated, unreachable by the scanner, or superseded).",
      );
      lines.push("");
      for (const r of delta.resolved) {
        lines.push(
          `- **[RESOLVED]** \`${escapeMdCell(r.id)}\` — ${escapeMdCell(r.title)} (${escapeMdCell(r.stride)} / ${escapeMdCell(r.severity)})`,
        );
      }
      lines.push("");
    } else {
      lines.push("No findings from the previous baseline moved to **resolved** this run.");
      lines.push("");
    }
  }

  if (sigsForToc.length > 0) {
    lines.push("## Static security signals (code scan)");
    lines.push("");
    lines.push(
      "Deterministic pattern matches from the analyzer. **Triage these first** — they ground LLM threats in real mechanisms and paths.",
    );
    lines.push("");
    lines.push("| Signal | Severity | Path | Summary |");
    lines.push("| --- | :---: | --- | --- |");
    for (const s of sigsForToc) {
      lines.push(
        `| ${escapeMdCell(s.id)} | ${escapeMdCell(s.severity)} | \`${escapeMdCell(s.path)}\` | ${escapeMdCell(s.summary)} |`,
      );
    }
    lines.push("");
  }

  const arch = resolveArchitectureRows(systemModel, threats);
  const actors = resolveThreatActorRows(threats);

  lines.push("## Data flows and trust boundaries");
  lines.push("");
  lines.push(`*${arch.sourceNote}*`);
  lines.push("");
  if (arch.rows.length > 0) {
    lines.push("| Boundary / flow | From | To |");
    lines.push("| --- | --- | --- |");
    for (const r of arch.rows) {
      lines.push(
        `| ${escapeMdCell(r.boundary_name)} | ${escapeMdCell(r.from_component)} | ${escapeMdCell(r.to_component)} |`,
      );
    }
  } else {
    lines.push("*No rows — supply architecture context or ensure `flow_graph` is populated.*");
  }
  lines.push("");

  lines.push("## Threat sources");
  lines.push("");
  lines.push(
    actors.isTailored
      ? "*Tailored to this application (LLM).*"
      : "*Generic categories for SDLC review — replace examples with your deployment specifics.*",
  );
  lines.push("");
  lines.push("| Category | Description | Example |");
  lines.push("| --- | --- | --- |");
  for (const a of actors.rows) {
    lines.push(
      `| ${escapeMdCell(a.category)} | ${escapeMdCell(a.description)} | ${escapeMdCell(a.example)} |`,
    );
  }
  lines.push("");

  if (hasLangs && langs && typeof langs === "object" && !Array.isArray(langs)) {
    lines.push("## Language inventory");
    lines.push("");
    lines.push(`| Language | Files |`);
    lines.push(`| --- | ---: |`);
    for (const [k, v] of Object.entries(langs as Record<string, unknown>)) {
      lines.push(`| ${k} | ${v} |`);
    }
    lines.push("");
  }

  if (hasGo && gs && typeof gs === "object") {
    lines.push("## Go / HTTP summary (best-effort)");
    lines.push("");
    lines.push(`| Metric | Value |`);
    lines.push(`| --- | --- |`);
    if (typeof gs.route_count === "number") {
      lines.push(`| API endpoint count (heuristic) | ${gs.route_count} |`);
    }
    if (typeof gs.http_route_count === "number") {
      lines.push(`| HTTP routes detected | ${gs.http_route_count} |`);
    }
    if (typeof gs.grpc_route_count === "number") {
      lines.push(`| gRPC methods detected | ${gs.grpc_route_count} |`);
    }
    if (Array.isArray(gs.frameworks_detected)) {
      lines.push(`| Frameworks detected | ${(gs.frameworks_detected as string[]).join(", ") || "—"} |`);
    }
    if (Array.isArray(gs.database_hints)) {
      lines.push(`| Data-store hints | ${(gs.database_hints as string[]).join(", ") || "—"} |`);
    }
    lines.push("");
  }

  if (hasMermaid) {
    lines.push("## Architecture / trust flow (Mermaid)");
    lines.push("");
    lines.push("```mermaid");
    lines.push(mermaidPreview);
    lines.push("```");
    lines.push("");
  }

  if (hasAnalystNotes && threats.notes?.trim()) {
    lines.push("## Analyst notes");
    lines.push("");
    lines.push(threats.notes.trim());
    lines.push("");
  }

  lines.push("## STRIDE threat register");
  lines.push("");
  if (delta != null) {
    lines.push("| Δ | ID | STRIDE | Severity | Title | Related paths |");
    lines.push("| :---: | --- | :---: | :---: | --- | --- |");
    for (const t of threats.threats) {
      const paths =
        t.related_paths.length > 0
          ? t.related_paths.map((p) => `\`${p}\``).join("<br>")
          : "—";
      const key = findingKeyForThreat(t, sigsForToc);
      const st = delta.statusByKey[key] ?? "NEW";
      const badge = st === "NEW" ? "NEW" : "UNCHANGED";
      lines.push(
        `| ${badge} | ${escapeMdCell(t.id)} | ${t.stride} | ${t.severity} | ${escapeMdCell(t.title)} | ${paths} |`,
      );
    }
  } else {
    lines.push("| ID | STRIDE | Severity | Title | Related paths |");
    lines.push("| --- | :---: | :---: | --- | --- |");
    for (const t of threats.threats) {
      const paths =
        t.related_paths.length > 0
          ? t.related_paths.map((p) => `\`${p}\``).join("<br>")
          : "—";
      lines.push(
        `| ${escapeMdCell(t.id)} | ${t.stride} | ${t.severity} | ${escapeMdCell(t.title)} | ${paths} |`,
      );
    }
  }
  lines.push("");

  lines.push("## Detailed findings");
  lines.push("");
  for (const t of threats.threats) {
    const key = findingKeyForThreat(t, sigsForToc);
    const st = delta?.statusByKey[key];
    const badge =
      delta && st === "NEW"
        ? "**[NEW]** "
        : delta && st === "UNCHANGED"
          ? "**[UNCHANGED]** "
          : "";
    lines.push(`### ${badge}${t.id} — ${escapeMdHeading(t.title)}`);
    lines.push("");
    lines.push(`- **STRIDE:** ${t.stride} (${strideLabel(t.stride)})  `);
    const linked = signalsMatchingThreat(t, sigsForToc);
    if (linked.length > 0) {
      lines.push(
        `- **Static signals:** ${linked.map((s) => `\`${s.id}\` (${s.severity})`).join(", ")}  `,
      );
    }
    lines.push(`- **Severity:** ${t.severity}  `);
    lines.push("");
    lines.push("**Description**");
    lines.push("");
    lines.push(t.description.trim() || "—");
    lines.push("");

    if (t.attack_scenario?.trim()) {
      lines.push("**Attack scenario**");
      lines.push("");
      lines.push(t.attack_scenario.trim());
      lines.push("");
    }
    if (t.prerequisites?.trim()) {
      lines.push("**Prerequisites**");
      lines.push("");
      lines.push(t.prerequisites.trim());
      lines.push("");
    }
    if (t.cwe_candidates.length > 0) {
      lines.push("**CWE candidates (triage)**");
      lines.push("");
      for (const c of t.cwe_candidates) {
        lines.push(`- ${escapeMdCell(c)}`);
      }
      lines.push("");
    }
    if (t.likelihood_rationale?.trim()) {
      lines.push("**Likelihood rationale**");
      lines.push("");
      lines.push(t.likelihood_rationale.trim());
      lines.push("");
    }
    if (t.impact_rationale?.trim()) {
      lines.push("**Impact rationale**");
      lines.push("");
      lines.push(t.impact_rationale.trim());
      lines.push("");
    }
    if (t.detection_and_monitoring?.trim()) {
      lines.push("**Detection and monitoring**");
      lines.push("");
      lines.push(t.detection_and_monitoring.trim());
      lines.push("");
    }

    if (t.immediate_actions.length > 0) {
      lines.push("**Immediate actions**");
      lines.push("");
      for (const a of t.immediate_actions) {
        lines.push(`- ${a}`);
      }
      lines.push("");
    }
    if (t.mitigations.length > 0) {
      lines.push("**Mitigations**");
      lines.push("");
      for (const m of t.mitigations) {
        lines.push(`- ${m}`);
      }
      lines.push("");
    }
    if (t.verification?.trim()) {
      lines.push("**Verification**");
      lines.push("");
      lines.push(t.verification.trim());
      lines.push("");
    }
    if (t.references.length > 0) {
      lines.push("**References**");
      lines.push("");
      for (const r of t.references) {
        lines.push(`- [${escapeMdCell(r.label)}](${r.url})`);
      }
      lines.push("");
    }

    const dive = deepDiveById[t.id]?.trim();
    if (dive) {
      lines.push("#### Deep-dive (LLM)");
      lines.push("");
      lines.push(formatDeepDiveForDisplay(dive));
      lines.push("");
    }

    lines.push("---");
    lines.push("");
  }

  if (includeRef) {
    lines.push("## STRIDE reference (CWE / OWASP pointers)");
    lines.push("");
    lines.push(
      "Curated pointers for **triage and training** — not a substitute for your org’s risk methodology or compliance mapping. CWE entries are summarized from public MITRE material.",
    );
    lines.push("");
    for (const k of STRIDE_ORDER) {
      const ref = STRIDE_REFERENCE[k];
      if (!ref) {
        continue;
      }
      lines.push(`### ${k} — ${strideLabel(k)}`);
      lines.push("");
      lines.push(ref.summary);
      lines.push("");
      lines.push("| CWE | Name |");
      lines.push("| --- | --- |");
      for (const c of ref.cwes) {
        lines.push(`| ${c.id} | ${escapeMdCell(c.name)} |`);
      }
      lines.push("");
      lines.push("**OWASP / cheat sheets**");
      lines.push("");
      for (const o of ref.owasp) {
        lines.push(`- [${escapeMdCell(o.label)}](${o.url})`);
      }
      lines.push("");
    }
  }

  lines.push("## Disclaimer");
  lines.push("");
  lines.push(
    "Automated threat models can be incomplete or wrong (e.g. protocol mismatches). Use this artifact as a **starting point** for review, not as the sole basis for risk acceptance.",
  );
  lines.push("");

  return lines.join("\n");
}

function strideLabel(letter: string): string {
  const m: Record<string, string> = {
    S: "Spoofing",
    T: "Tampering",
    R: "Repudiation",
    I: "Information disclosure",
    D: "Denial of service",
    E: "Elevation of privilege",
  };
  return m[letter] ?? letter;
}

function escapeMdCell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function escapeMdHeading(s: string): string {
  return s.replace(/\n/g, " ").trim();
}
