import { randomUUID } from "node:crypto";

import type { ThreatOutput } from "./schemas.js";

export type ThreatDragonExportOptions = {
  title: string;
  owner?: string;
  description?: string;
};

/**
 * Builds a Threat Dragon v2-compatible JSON document from ThreatLens threat output.
 * Open in OWASP Threat Dragon (web/desktop): File → Open, or Git sync per TD docs.
 * @see https://github.com/OWASP/threat-dragon
 */
export function buildThreatDragonModel(
  output: ThreatOutput,
  opts: ThreatDragonExportOptions,
): Record<string, unknown> {
  const owner = opts.owner ?? "ThreatLensAI";
  const processId = randomUUID();
  const tdThreats = output.threats.map(toTDThreat);

  return {
    summary: {
      title: opts.title,
      owner,
      description: opts.description ?? "Generated by ThreatLensAI for editing in OWASP Threat Dragon.",
      id: 0,
    },
    detail: {
      contributors: [],
      diagrams: [
        {
          title: "ThreatLens import",
          thumbnail: "",
          diagramType: "STRIDE",
          id: 0,
          diagramJson: {
            cells: [
              {
                type: "tm.Process",
                size: { width: 200, height: 120 },
                position: { x: 140, y: 140 },
                angle: 0,
                id: processId,
                z: 1,
                threats: tdThreats,
                outOfScope: false,
                hasOpenThreats: tdThreats.length > 0,
                attrs: {
                  ".element-shape": {
                    class: "element-shape hasOpenThreats isInScope",
                  },
                  text: { text: "Imported scope" },
                  ".element-text": {
                    class: "element-text hasOpenThreats isInScope",
                  },
                },
              },
            ],
          },
          size: { height: 480, width: 720 },
        },
      ],
    },
  };
}

export function threatDragonJSONString(
  output: ThreatOutput,
  opts: ThreatDragonExportOptions,
): string {
  return JSON.stringify(buildThreatDragonModel(output, opts), null, 2);
}

function toTDThreat(th: ThreatOutput["threats"][number]) {
  const mitigation = [th.mitigations.join("\n\n"), th.immediate_actions.length ? `\n\nNext: ${th.immediate_actions.join(" | ")}` : ""]
    .join("")
    .trim();
  const desc = [th.description, th.verification ? `\n\nVerification: ${th.verification}` : ""].join("").trim();
  return {
    status: "Open",
    severity: mapSeverity(th.severity),
    title: th.title,
    type: strideToTDType(th.stride),
    description: desc,
    mitigation: mitigation || "Track in backlog; add controls as needed.",
  };
}

function mapSeverity(s: string): string {
  switch (s) {
    case "LOW":
      return "Low";
    case "MEDIUM":
      return "Medium";
    case "HIGH":
      return "High";
    case "CRITICAL":
      return "Critical";
    default:
      return "Medium";
  }
}

function strideToTDType(stride: string): string {
  const m: Record<string, string> = {
    S: "Spoofing",
    T: "Tampering",
    R: "Repudiation",
    I: "Information disclosure",
    D: "Denial of service",
    E: "Elevation of privilege",
  };
  return m[stride] ?? "Tampering";
}
